server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Prioridad para la política de privacidad
    location /privacy_policy.html {
        alias /usr/share/nginx/html/privacy_policy.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location / {
        root /usr/share/nginx/html;
        # Redirigir peticiones de activos que falten el prefijo /assets/
        rewrite ^/assets/images/(.*)$ /assets/assets/images/$1 break;
        try_files $uri $uri/ /index.html;
    }

    # No cache para HTML para evitar problemas con versiones antiguas
    location ~* \.html$ {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri /index.html;
    }

    # Configuración de compresión Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;
    gzip_disable "MSIE [1-6]\.";

    # Cache Control para activos estáticos (imágenes, fuentes, iconos, css, js)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
